server:
  port: 54293

spring:
  application:
    name: PLAYER-SERVER

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  key: my_custom_token

default:
  message: player-service에서 사용될 properties
